name: app_beh
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.8.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0  # Material Design 3 폰트 지원
  flutter_riverpod: ^2.4.9  # 상태 관리 (추후 퀘스트 데이터 관리용)
  fl_chart: ^0.65.0  # 차트 시각화를 위한 라이브러리
  table_calendar: ^3.0.9 # 캘린더 라이브러리
  intl: ^0.18.0 # 캘린더 관련 언어 설정 라이브러리
  flutter_svg: ^2.0.9
  image_picker: ^1.1.2
  dio: ^5.4.0  # 버전은 최신으로
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - .env  # .env 파일을 assets에 추가
    - assets/images/    # 이미지 파일들이 있는 폴더
    - assets/icons/     # 아이콘 파일들이 있는 폴더